# Generated by Django 3.1.7 on 2021-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210325_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='worker',
            name='professions',
        ),
        migrations.AddField(
            model_name='worker',
            name='professions',
            field=models.ManyToManyField(to='core.Profession'),
        ),
    ]
