# Generated by Django 3.2.5 on 2021-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
        migrations.AddField(
            model_name='worker',
            name='cities',
            field=models.ManyToManyField(to='core.City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
