# Generated by Django 3.2.5 on 2021-07-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
